//Auth
export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"

export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR"

export const SIGNIN_REQUEST = "SIGNIN_REQUEST"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const SET_TOKEN_NOTIFY_SUCCESS = "SET_TOKEN_NOTIFY_SUCCESS"
export const SET_TOKEN_NOTIFY_ERROR = "SET_TOKEN_NOTIFY_ERROR"

export const INIT_TOKEN_NOTIFY = "INIT_TOKEN_NOTIFY"

//Profile
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR"

//Society
export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST"
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS"
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR"

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST"
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS"
export const REMOVE_FRIEND_ERROR = "REMOVE_FRIEND_ERROR"

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST"
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS"
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR"

export const GET_FRIENDS_ID_SUCCESS = "GET_FRIENDS_ID_SUCCESS"
export const GET_FRIENDS_ID_ERROR = "GET_FRIENDS_ID_ERROR"

export const GET_PEOPLE_REQUEST = "GET_PEOPLE_REQUEST"
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS"
export const GET_PEOPLE_ERROR = "GET_PEOPLE_ERROR"

//buttons
export const CREATE_BUTTON_REQUEST = "CREATE_BUTTON_REQUEST"
export const CREATE_BUTTON_SUCCESS = "CREATE_BUTTON_SUCCESS"
export const CREATE_BUTTON_ERROR = "CREATE_BUTTON_ERROR"

export const GET_MY_BUTTON_REQUEST = "GET_MY_BUTTON_REQUEST"
export const GET_MY_BUTTON_SUCCESS = "GET_MY_BUTTON_SUCCESS"
export const GET_MY_BUTTON_ERROR = "GET_MY_BUTTON_ERROR"

export const GET_BUTTONS_REQUEST = "GET_BUTTONS_REQUEST"
export const GET_BUTTONS_SUCCESS = "GET_BUTTONS_SUCCESS"
export const GET_BUTTONS_ERROR = "GET_BUTTONS_ERROR"

export const UPDATE_BUTTON_SUCCESS = "UPDATE_BUTTON_SUCCESS"
export const UPDATE_BUTTON_ERROR = "UPDATE_BUTTON_ERROR"

export const GET_CURRENT_BUTTON_SUCCESS = "GET_CURRENT_BUTTON_SUCCESS"
export const GET_CURRENT_BUTTON_ERROR = "GET_CURRENT_BUTTON_ERROR"

export const REMOVE_FRIEND_BUTTON_SUCCESS = "REMOVE_FRIEND_BUTTON_SUCCESS"
export const REMOVE_FRIEND_BUTTON_ERROR = "REMOVE_FRIEND_BUTTON_ERROR"

//FOR PAGES

//Freind page
export const LIVE_FROM_FRIEND_PAGE = "LIVE_FROM_FRIEND_PAGE"

//Current button page
export const LEAVE_CURRENT_BUTTON = "LEAVE_CURRENT_BUTTON"
// buttons page
export const SWITCH_BUTTONS_IN_BUTTONS = "SWITCH_BUTTONS_IN_BUTTONS"
